### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by ionite34** [brandtbucher/pycapi#3]
Current does not seem to build on 3.11, are there plans for 3.11 support?

**Comment by brandtbucher** [comment]
Yeah, just hasn't been a priority since nobody asked for it yet. ;)

I'll take a look at this sometime in the next few days... should be as simple as adding version guards for any removed APIs, adding 3.11 to CI, and cutting a new release.

**Comment by brandtbucher** [comment]
[Done!](https://pypi.org/project/pycapi/0.82.1/)

Thanks for opening the issue! Let me know if you encounter any other problems.
