### ISSUE TITLE
Py*_stgdict are not exposed.

### ISSUE THREAD

**Issue by kdschlosser** [brandtbucher/pycapi#4]
Functions like ` PyObject_stgdict` and `PyType_stgdict` 

They are not static functions and I would imagine they would be available. They are not prefixed with an underscore which indicates they are public. The functions are declared as `extern` in ctypes.h as well.

**Comment by brandtbucher** [comment]
Eh, sorry, those aren't part of CPython's documented public [C API](https://docs.python.org/3/c-api/index.html). Adding them feels out of scope for this project.
